name: l_flutter_example
description: Flutter [L]ogger example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  l:
    path: '../../'

flutter:
  uses-material-design: true
